La idea es poder ver como esta estructurados los datos.

[contraloria.cl](https://www.contraloria.cl/portalweb/web/cgr/base-de-datos-municipales)

In [11]:
import pandas as pd

patrimonial_2025_df = pd.read_excel('data/BD Patrimonial 2025_09-06-2026.xlsx')
patrimonial_2025_df

,Ejercicio,Región,Cod Municipio,Nombre Municipio,Cod Serv Incorporado,Nombre Serv Incorporado,Cod Título,Nombre Título,Cod Grupo,Nombre Grupo,...,Debe Octubre,Haber Octubre,Debe Noviembre,Haber Noviembre,Debe Diciembre,Haber Diciembre,Debe Total,Haber Total,Saldo acum,Saldo Final
0,2025,I,7501,Iquique,1,Gestión Municipal,1,ACTIVO,11,RECURSOS DISPONIBLES,...,10058745511,9985798181,6755415024,6501872283,10292865389,10340387144,116385106879,116137917392,247189487,563124857
1,2025,I,7501,Iquique,1,Gestión Municipal,1,ACTIVO,11,RECURSOS DISPONIBLES,...,9871664926,11266671268,6439127733,10207442353,10295040444,10526041855,114544061595,117828286072,-3284224477,27886417715
2,2025,I,7501,Iquique,1,Gestión Municipal,1,ACTIVO,11,RECURSOS DISPONIBLES,...,114694169,193857872,64109208,114694169,47799175,64109208,4448867150,4445899060,2968090,47799175
3,2025,I,7501,Iquique,1,Gestión Municipal,1,ACTIVO,11,RECURSOS DISPONIBLES,...,0,0,0,0,0,0,0,0,0,90440000
4,2025,I,7501,Iquique,1,Gestión Municipal,1,ACTIVO,11,RECURSOS DISPONIBLES,...,9732724,9732724,3920457,3920457,2598931,2598931,66142773,66142773,0,14910088
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73491,2025,XVI,9021,San Nicolás,3,Salud,5,GASTOS PATRIMONIALES,53,GASTOS OPERACIONALES,...,0,0,0,0,3123750,0,10426383,0,10426383,10426383
73492,2025,XVI,9021,San Nicolás,3,Salud,5,GASTOS PATRIMONIALES,53,GASTOS OPERACIONALES,...,0,0,0,0,0,0,6059762,0,6059762,6059762
73493,2025,XVI,9021,San Nicolás,3,Salud,5,GASTOS PATRIMONIALES,53,GASTOS OPERACIONALES,...,22431509,0,26919542,0,60532826,0,160242117,0,160242117,160242117
73494,2025,XVI,9021,San Nicolás,3,Salud,5,GASTOS PATRIMONIALES,53,GASTOS OPERACIONALES,...,438783,0,472723,0,837111,0,4881708,0,4881708,4881708
73495,2025,XVI,9021,San Nicolás,3,Salud,5,GASTOS PATRIMONIALES,56,OTROS GASTOS PATRIMONIALES,...,0,0,0,0,0,0,23590434,0,23590434,23590434

In [12]:
presupuesto_2025_df = pd.read_excel('data/BD Presupuestaria 2025_09-06-2026.xlsx')
presupuesto_2025_df

,Ejercicio,Moneda,Región,Cod Municipio,Nombre Municipio,Cod Serv Incorporado,Nombre Serv Incorporado,Cod Subárea,Nombre Subárea,Cod Tipo Cuenta,...,Porpercibir Abril,Porpercibir Mayo,Porpercibir Junio,Porpercibir Julio,Porpercibir Agosto,Porpercibir Septiembre,Porpercibir Octubre,Porpercibir Noviembre,Porpercibir Diciembre,Porpercibir acum
0,2025,CLP,I,7502,Alto Hospicio,1,Gestión Municipal,0,Sin Subárea,1,...,0,0,0,0,0,0,0,0,0,0
1,2025,CLP,I,7502,Alto Hospicio,1,Gestión Municipal,0,Sin Subárea,1,...,7239302,-15158643,24259831,130948929,0,32957264,16557686,38894516,26910444,26910444
2,2025,CLP,I,7502,Alto Hospicio,1,Gestión Municipal,0,Sin Subárea,1,...,0,0,0,0,0,0,0,0,0,0
3,2025,CLP,I,7502,Alto Hospicio,1,Gestión Municipal,0,Sin Subárea,1,...,0,0,0,0,0,2134509,2134509,2134509,0,0
4,2025,CLP,I,7502,Alto Hospicio,1,Gestión Municipal,0,Sin Subárea,1,...,0,0,0,0,0,2108150,2108150,2108150,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162556,2025,CLP,XVI,9019,Ñiquén,3,Salud,0,Sin Subárea,2,...,0,0,0,0,0,0,0,0,0,0
162557,2025,CLP,XVI,9019,Ñiquén,3,Salud,0,Sin Subárea,2,...,0,0,0,0,0,0,0,0,0,0
162558,2025,CLP,XVI,9019,Ñiquén,3,Salud,0,Sin Subárea,2,...,0,0,0,0,0,0,0,0,0,0
162559,2025,CLP,XVI,9019,Ñiquén,3,Salud,0,Sin Subárea,2,...,0,0,0,0,0,0,0,0,0,0
162560,2025,CLP,XVI,9019,Ñiquén,3,Salud,0,Sin Subárea,2,...,0,0,0,0,0,0,0,0,0,0

In [13]:
presupuesto_2025_df.describe()

,Ejercicio,Cod Municipio,Cod Serv Incorporado,Cod Subárea,Cod Tipo Cuenta,Cod Subtítulo,Cod Ítem,Cod Asignación,Cod Subasignación,Cod Subsubasignación,...,Porpercibir Abril,Porpercibir Mayo,Porpercibir Junio,Porpercibir Julio,Porpercibir Agosto,Porpercibir Septiembre,Porpercibir Octubre,Porpercibir Noviembre,Porpercibir Diciembre,Porpercibir acum
count,162561.0,162561.000000,162561.000000,162561.000000,162561.000000,162561.000000,162561.000000,162561.000000,1.625610e+05,1.625610e+05,...,1.625610e+05,1.625610e+05,1.625610e+05,1.625610e+05,1.625610e+05,1.625610e+05,1.625610e+05,1.625610e+05,1.625610e+05,1.625610e+05
mean,2025.0,8277.152189,1.577715,1.099009,1.850456,20.353972,5.991419,6059.738597,6.059759e+06,6.059759e+09,...,9.239131e+06,9.131117e+06,9.181403e+06,1.042779e+07,9.977786e+06,9.845160e+06,9.139130e+06,8.981941e+06,8.947430e+06,9.489674e+06
std,0.0,377.849164,0.847865,1.512964,0.356625,6.259115,14.006025,14038.683141,1.403868e+07,1.403868e+10,...,4.393853e+08,4.359209e+08,4.322524e+08,4.506358e+08,4.367169e+08,4.335835e+08,4.035959e+08,4.005188e+08,3.973448e+08,4.256892e+08
min,2025.0,7501.000000,1.000000,0.000000,1.000000,3.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,...,-1.991298e+09,-1.991543e+09,-1.991691e+09,-1.968263e+09,-1.975168e+09,-1.975500e+09,-1.976509e+09,-1.977555e+09,-1.139334e+09,-1.139334e+09
25%,2025.0,8008.000000,1.000000,0.000000,2.000000,21.000000,2.000000,2000.000000,2.000000e+06,2.000000e+09,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2025.0,8223.000000,1.000000,1.000000,2.000000,22.000000,3.000000,3009.000000,3.009001e+06,3.009001e+09,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,2025.0,8602.000000,2.000000,1.000000,2.000000,22.000000,6.000000,6001.000000,6.001000e+06,6.001000e+09,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,2025.0,9021.000000,4.000000,6.000000,2.000000,35.000000,99.000000,99999.000000,9.999900e+07,9.999900e+10,...,1.216098e+11,1.212416e+11,1.206656e+11,1.199500e+11,1.195919e+11,1.192363e+11,1.188430e+11,1.186176e+11,1.179330e+11,1.179330e+11

Columnas usables:
- `Cod Municipio`
- `Cod Serv Incorporado`
- `Cod Tipo Cuenta`